// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAfterTime(arg1) {
  return window['go']['main']['App']['GetAfterTime'](arg1);
}

export function GetAllSchools() {
  return window['go']['main']['App']['GetAllSchools']();
}

export function GetWithKeyWords(arg1) {
  return window['go']['main']['App']['GetWithKeyWords'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function StartCrawler() {
  return window['go']['main']['App']['StartCrawler']();
}
