// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {util} from '../models';

export function GetAfterTime(arg1:string):Promise<Array<util.School>>;

export function GetAllSchools():Promise<Array<util.School>>;

export function GetWithKeyWords(arg1:Array<string>):Promise<Array<util.School>>;

export function Greet(arg1:string):Promise<string>;

export function StartCrawler():Promise<void>;
